# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewAppSplashScreenCocoaPodsTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewAppSplashScreenCocoaPodsTest

  target 'NewAppSplashScreenCocoaPodsTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewAppSplashScreenCocoaPodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NewAppSplashScreenCocoaPodsTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewAppSplashScreenCocoaPodsTest-tvOS

  target 'NewAppSplashScreenCocoaPodsTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
